# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

description:  前端 javascript es6 css html
url: http://mlxiao.com

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags
  # Categories: /categories
  About: /about

# site search option
search: true

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# ===========================================
# Social links Settings
# ===========================================
social:
  email: martin.xiao.cn@gmail.com
  stack-overflow:
  twitter:
  facebook:
  github: https://github.com/mlxiao93
  weibo:
  zhihu:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: b749a7ec8f4ce4e8913350bbc7a424d8
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname: mlxiao
# Disqus
# disqus_shortname: https-mlxiao93-github-io-blog


# ===========================================
# Version
# ===========================================
version: 2.1.x

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
